### ISSUE TITLE
Help with daemond and others.

### ISSUE THREAD

**Issue by Artzalez** [cryptofun/honey#15]
When Honey-qt in linux ?
Example:
![imagen](https://user-images.githubusercontent.com/30190276/28654780-4e96a91a-7297-11e7-9075-1e5f9531e2ec.png)
Im using a daemond compiled but i not can connect to daemond in my pool any idea parammeters i need ?
**i have: ./honeyd -server -daemon -datadir=/var/honey/**
I recive error 401 and when i use the wallet in windows and configure all, i have equally problem.

**Comment by Artzalez** [comment]
ERROR Failed to connect to 192.168.138 port 40639: Connection refused | This is a error from my pool (192.168.1.58)
This is my honey.conf
`listen=1
server=1
daemond=1
port=40638
rcpport=40639
rpcuser=DHoney
rpcpassword=QWERTY
rcpthreads=8
rcpallowip=192.168.1.58
rcpconnect=192.168.1.38
gen=0`

**Comment by Artzalez** [comment]
i use the compiled honeyd with this parammeters and this say
![imagen](https://user-images.githubusercontent.com/30190276/28657231-5e1ca998-72a6-11e7-9dc0-55f9c1bc61c4.png)
and close

**Comment by cryptostiltskin** [comment]
Please add this to your honey.conf and restart your client.

`addnode=154.16.7.186`
