### ISSUE TITLE
Wallet.Dat Corrupt w/2.0.1.1

### ISSUE THREAD

**Issue by joesixpack** [cryptofun/honey#17]
![image](https://user-images.githubusercontent.com/23145642/30769361-837a9f18-9fcb-11e7-9827-40688cb7dc39.png)

**Comment by cryptostiltskin** [comment]
export your private keys from the old wallet and import them to your new wallet

**Comment by joesixpack** [comment]
That worked (actually, export is greyed out so I did it manual), but now:

![image](https://user-images.githubusercontent.com/23145642/30776898-d648710a-a063-11e7-9ac1-01572b3942c8.png)

**Comment by cryptostiltskin** [comment]
new wallet will be available soon with fixes. closing this for now. reopen if the new wallet does not resolve your issue.
