### ISSUE TITLE
building ubuntu 14 boost 1_54 gives error

### ISSUE THREAD

**Issue by bumbacoin** [cryptofun/honey#19]
the error given is

obj/walletdb.o: In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status

**Comment by bumbacoin** [comment]
work around using

make -f makefile.unix USE_UPNP=- CXXFLAGS=-DBOOST_NO_CXX11_SCOPED_ENUMS

**Comment by bumbacoin** [comment]
replacing this in walletdb.cpp #748 
also allows building

#if BOOST_VERSION >= 158000
                    filesystem::copy_file(pathSrc, pathDest, filesystem::copy_option::overwrite_if_exists);
#else
                    std::ifstream  src(pathSrc.string(), std::ios::binary);
                    std::ofstream  dst(pathDest.string(),   std::ios::binary);
                    dst << src.rdbuf();
#endif


i have commented on teh commit which removes it
https://github.com/cryptofun/honey/commit/3c732edc7f64793e3ef4a2caa29dc3caa17e4321#comments

**Comment by cryptostiltskin** [comment]
Fixed in new commits
