### ISSUE TITLE
building in ubuntu 14.04 error

### ISSUE THREAD

**Issue by bumbacoin** [cryptofun/honey#7]
new update to mining.cpp results in error

miner.cpp: In function ‘CBlock* CreateNewBlock(CReserveKey&, bool, int64_t*)’:
miner.cpp:106:5: error: ‘unique_ptr’ was not declared in this scope
     unique_ptr<CBlock> pblock(new CBlock());

requires
g++ -std=c++11
to compile

**Comment by bumbacoin** [comment]
oops,
results in new error

obj/walletdb.o: In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'

**Comment by bumbacoin** [comment]
i also used -DBOOST_NO_CXX11_SCOPED_ENUMS

makefile ended up as using 
```

xCXXFLAGS=-O2 $(EXT_OPTIONS) -pthread -Wall -Wextra -std=c++11 -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter \
    $(DEBUGFLAGS) $(DEFS) $(HARDENING) $(CXXFLAGS) -DBOOST_NO_CXX11_SCOPED_ENUMS

```

**Comment by cryptostiltskin** [comment]
oh i had used 

`find . -type f -exec sed -i 's/unique_ptr/auto_ptr/g' {} +`

**Comment by bumbacoin** [comment]
the changes breaks the mac build in my current environment too.

qtcreator suggesting changing to boost::csbl::unique_ptr
which works.

eg https://github.com/cryptofun/honey/blob/master/src/rpcmining.cpp#L255
`    unique_ptr<CBlock> pblock(CreateNewBlock(*pMiningKey, true, &nFees));
`
to
`    boost::csbl::unique_ptr<CBlock> pblock(CreateNewBlock(*pMiningKey, true, &nFees));
`

this doesnt help with ubuntu issue though.

**Comment by cryptostiltskin** [comment]
just run this command from sources folder to fix it

`find . -type f -exec sed -i 's/unique_ptr/auto_ptr/g' {} +`

**Comment by gjhiggins** [comment]
You could try this, it works for me with boost 1.58 on Ubuntu:

    + #include <boost/move/unique_ptr.hpp>

...

    - auto_ptr<CBlock> pblock(new CBlock());
    + boost::movelib::unique_ptr<CBlock> pblock(new CBlock());

**Comment by ghost** [comment]
w.r.t. the `copy_file` issue on Ubuntu, I picked up this fix from PIVX:

https://github.com/slimcoin-project/Slimcoin/commit/4218e2071853c2dbd82d15dafd7b71344aed7a8b

might work for you

**Comment by cryptostiltskin** [comment]
fixed in master. new release soon
